spring:
    application:
        name: spring-boot-kotlin-practice
    docker:
        compose:
            file: payment/docker/docker-compose.yaml
            enabled: true
            lifecycle-management: start-and-stop
            stop:
                command: down
                timeout: 1m
            skip:
                in-tests: false
    datasource:
        url: jdbc:mysql://localhost:3306/mydb
        username: practice
        password: practice
    sql:
        init:
            mode: always
    data:
        redis:
            host: localhost
            port: 6380